// react/src/ui/components/LoginView.tsx
import React from 'react';
import { LoginViewProps } from 'js-obfuscation-vanilla';

export class LoginView extends React.Component<LoginViewProps> {
    private emailInput?: HTMLInputElement | null = null;
    private passwordInput?: HTMLInputElement | null = null;

    /**
     * Handles requesting authenticating based the inputted credentials
     */
    handleLogin = () => {
        const email = (this.emailInput?.value || '').trim();
        const password = (this.passwordInput?.value || '').trim();
        this.props.onLogin(email, password);
    };

    render() {
        return (
            <div>
                <h1>Login</h1>
                <input
                    type="text"
                    name="email"
                    placeholder="Email"
                    ref={input => {
                        this.emailInput = input as HTMLInputElement | null;
                    }}
                />
                <input
                    type="password"
                    name="password"
                    placeholder="Password"
                    ref={input => {
                        this.passwordInput = input as HTMLInputElement | null;
                    }}
                />
                <button onClick={this.handleLogin}>Login</button>
            </div>
        );
    }
}

// svelte/src/ui/components/LoginView.svelte
<script lang="ts">
    export let onLogin: (email: string, password: string) => void;

    let email = "";
    let password = "";

    const handleLogin = () => {
        onLogin(email.trim(), password.trim());
    };
</script>

<div>
    <h1>Login</h1>
    <input type="text" bind:value={email} placeholder="Email" />
    <input type="password" bind:value={password} placeholder="Password" />
    <button on:click={handleLogin}>Login</button>
</div>
