// svelte/src/ui/components/MenuView.svelte
<script lang="ts">
    export let onLogout: () => void;
    export let onAccount: () => void;
    export let onOrders: () => void;
</script>

<div>
    <a href="#" on:click|preventDefault={onLogout}>Logout</a>
    <a href="#" on:click|preventDefault={onAccount}>Account</a>
    <a href="#" on:click|preventDefault={onOrders}>Orders</a>
</div>

// react/src/ui/components/MenuView.tsx
import React from 'react';
import { MenuViewProps } from 'js-obfuscation-vanilla';

/**
 * The class that handles rendering the menu
 */
export class MenuView extends React.Component<MenuViewProps> {
    render() {
        const { onLogout, onAccount, onOrders } = this.props;

        return (
            <div>
                <a className="link" href="#" data-name="logout" onClick={onLogout}>
                    Logout
                </a>
                <a className="link" href="#" data-name="account" onClick={onAccount}>
                    Account
                </a>
                <a className="link" href="#" data-name="orders" onClick={onOrders}>
                    Orders
                </a>
            </div>
        );
    }
}
