// svelte/src/ui/components/AccountView.svelte
<script lang="ts">
    import { getUserFullName, getFormattedDate, User } from '../../../../vanilla';
    export let user: User;
</script>

<div>
    <h1>Account Information</h1>
    <p><strong>Name:</strong> {getUserFullName(user)}</p>
    <p><strong>Email:</strong> {user.getEmail()}</p>
    <p><strong>Account created:</strong> {getFormattedDate(user.getCreatedDate())}</p>
    <p><strong>Last accessed:</strong> {getFormattedDate(user.getLastAccessedDate())}</p>
</div>

// solidjs/src/ui/components/AccountView.tsx
import { User, getFormattedDate, getUserFullName } from '../../../../vanilla';

export default function AccountView(props: { user: User }) {
    return (
        <div>
            <h1>Account Information</h1>
            <p>
                <strong>Name:</strong> {getUserFullName(props.user)}
            </p>
            <p>
                <strong>Email:</strong> {props.user.getEmail()}
            </p>
            <p>
                <strong>Account created:</strong> {getFormattedDate(props.user.getCreatedDate())}
            </p>
            <p>
                <strong>Last accessed:</strong> {getFormattedDate(props.user.getLastAccessedDate())}
            </p>
        </div>
    );
}
