// svelte/src/ui/components/MenuView.svelte
<script lang="ts">
    export let onLogout: () => void;
    export let onAccount: () => void;
    export let onOrders: () => void;
</script>

<div>
    <a href="#" on:click|preventDefault={onLogout}>Logout</a>
    <a href="#" on:click|preventDefault={onAccount}>Account</a>
    <a href="#" on:click|preventDefault={onOrders}>Orders</a>
</div>

// solidjs/src/ui/components/MenuView.tsx
export default function MenuView(props: { onLogout: () => void; onAccount: () => void; onOrders: () => void }) {
    return (
        <div>
            <a
                href="#"
                onClick={e => {
                    e.preventDefault();
                    props.onLogout();
                }}
            >
                Logout
            </a>
            <a
                href="#"
                onClick={e => {
                    e.preventDefault();
                    props.onAccount();
                }}
            >
                Account
            </a>
            <a
                href="#"
                onClick={e => {
                    e.preventDefault();
                    props.onOrders();
                }}
            >
                Orders
            </a>
        </div>
    );
}
