// svelte/src/ui/AppView.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { AppController, Order, User } from '../../../vanilla';

    import LoginView from './components/LoginView.svelte';
    import MenuView from './components/MenuView.svelte';
    import AccountView from './components/AccountView.svelte';
    import OrdersView from './components/OrdersView.svelte';

    const accountUI = new AppController();
    let activeView: 'login' | 'account' | 'orders' = 'login';
    let user: User | null = null;
    let orders: Order[] = [];

    const uiProps = accountUI.getUIProps();

    accountUI.connectUI({
        showAccount,
        showLogin,
        showOrders
    });

    async function showAccount() {
        user = uiProps.api.getCurrentUser();
        if (user) {
            activeView = 'account';
        } else {
            await showLogin();
        }
    }

    async function showLogin() {
        activeView = 'login';
    }

    async function showOrders() {
        if (!uiProps.api.getCurrentUser()) {
            return await showLogin();
        }
        orders = await uiProps.api.getOrders();
        activeView = 'orders';
    }
</script>

<div>
    <MenuView
        onLogout={uiProps.onLogout}
        onAccount={showAccount}
        onOrders={showOrders}
    />

    {#if activeView === 'login'}
        <LoginView onLogin={uiProps.onLogin} />
    {:else if activeView === 'account' && user}
        <AccountView {user} />
    {:else if activeView === 'orders'}
        <OrdersView {orders} />
    {/if}
</div>

// react/src/ui/AppView.tsx
import React, { JSX } from 'react';
import { UIInterface, UIProps } from 'js-obfuscation-vanilla';
import { LoginView } from './components/LoginView';
import { MenuView } from './components/MenuView';
import { AccountView } from './components/AccountView';
import { OrdersView } from './components/OrdersView';

/**
 * The class that handles rendering the UI using Vanilla JavaScript
 */
export class AppView extends React.Component<UIProps, { activeView: null | JSX.Element }> implements UIInterface {
    static element = 'app-view';

    // the menu view component
    private menuView: JSX.Element;

    constructor(props: UIProps) {
        super(props);

        // creating the initial state
        this.state = {
            activeView: null
        };

        // creating the menu view instance
        this.menuView = this.createMenu();
    }

    /**
     * Shows the account view for the current user if exists
     * If not, it will show the login form
     */
    async showAccount(): Promise<void> {
        const user = this.props.api.getCurrentUser();
        if (user === null) return await this.showLogin();

        this.setState({
            activeView: <AccountView user={user} />
        });
    }

    /**
     * Shows the login view
     */
    async showLogin(): Promise<void> {
        this.setState({
            activeView: <LoginView onLogin={this.props.onLogin} />
        });
    }

    /**
     * Shows the list of orders the current user has placed
     */
    async showOrders(): Promise<void> {
        const user = this.props.api.getCurrentUser();
        if (user === null) return await this.showLogin();

        // getting the list of orders for the current users
        const orders = await this.props.api.getOrders();

        this.setState({
            activeView: <OrdersView orders={orders} />
        });
    }

    /**
     * Creates the menu view instance
     */
    private createMenu(): JSX.Element {
        return <MenuView onLogout={() => this.showLogin()} onAccount={() => this.showAccount()} onOrders={() => this.showOrders()} />;
    }

    render() {
        return (
            <div>
                {this.menuView}
                {this.state?.activeView || null}
            </div>
        );
    }
}
